#MODEL:
model_name: eleven_22_14_18_decoder11
model_type: experimental2
num_classes: 19
ignore_value: 255
pretrained_backbone: False

#OPTIM:
epochs: 500
max_epochs: 500
resume: False
lr: 0.05
momentum: 0.9
weight_decay: 0.0001
class_weight: null
bn_weight_decay: False
bn_precise_stats: False
bn_precise_num_samples: 600
lr_scheduler: poly
poly_power: 0.9
warmup_iters: 3000
warmup_factor: 0.1

#TRAIN:
mixed_precision: True
runs: 1
run: 1
RNG_seed: 0
loss_type: cross_entropy
eval_while_train: True
exclude_classes: [14,15,16]

#benchmark
warmup_iter: 10
num_iter: 100
benchmark_loader: True
benchmark_model: True

#dataset
dataset_name: cityscapes
dataset_dir: cityscapes_dataset
batch_size: 8
train_min_size: 400
train_max_size: 1600
train_crop_size: [768,768]
val_input_size: 1024
val_label_size: 1024
aug_mode: randaug_reduced
resize_mode: uniform
edge_aware_crop: False
boost_rare_classes: False
num_workers: 6
class_uniform_pct: 0.5
train_split: train
val_split: val
max_eval: 600
validate_train_loader: False
eval_print_every: 10000
train_print_every: 10000

#checkpoint
log_path: './log_file/DW_6_221418_500e_dg_8'#命名规则：卷积方式.D_block有几层，是什么样子的，训练几个epoch，解码器decoder是啥样子的general-普通的，缩写为g，BS是多少
save_best_path: './pth_file/best_DW_6_221418_500e_dg_8.pth'
save_latest_path: './pth_file/latest_DW_6_221418_500e_dg_8.pth'
pretrained_path: ''
save_every_k_epochs: 25
save_last_k_epochs: 30
save_dir: checkpoints
log_dir: training_log
save_name: cityscapes_exp48_decoder26_1000_epoch_change
